version: "3.9"
# conexão web
services:
  web:
    build: .
    container_name: fastapi_web
    volumes:
    - .:/app  
    ports:
      - "8000:8000"
    
    env_file:
      - ./.env
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
      POSTGRES_HOST: db
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy  
# conexão db 
  db:
    image: postgres:15
    container_name: fastapi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5   
# conexão  pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: fastapi_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: