"""baseline pt-br schema

Revision ID: d619f21dfe99
Revises: 
Create Date: 2025-08-17 11:33:29.458212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd619f21dfe99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pessoas_email'), 'pessoas', ['email'], unique=True)
    op.create_index(op.f('ix_pessoas_id'), 'pessoas', ['id'], unique=False)
    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('checkin_type', sa.Enum('alegria', 'tristeza', 'angustia', 'magoa', 'ansiedade', name='moodtype'), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='ck_check_ins_score_range'),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_ins_id'), 'check_ins', ['id'], unique=False)
    op.create_index(op.f('ix_check_ins_pessoa_id'), 'check_ins', ['pessoa_id'], unique=False)
    op.create_table('contatos_emergencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contatos_emergencia_id'), 'contatos_emergencia', ['id'], unique=False)
    op.create_index(op.f('ix_contatos_emergencia_pessoa_id'), 'contatos_emergencia', ['pessoa_id'], unique=False)
    op.create_table('lembretes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lembretes_id'), 'lembretes', ['id'], unique=False)
    op.create_index(op.f('ix_lembretes_pessoa_id'), 'lembretes', ['pessoa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lembretes_pessoa_id'), table_name='lembretes')
    op.drop_index(op.f('ix_lembretes_id'), table_name='lembretes')
    op.drop_table('lembretes')
    op.drop_index(op.f('ix_contatos_emergencia_pessoa_id'), table_name='contatos_emergencia')
    op.drop_index(op.f('ix_contatos_emergencia_id'), table_name='contatos_emergencia')
    op.drop_table('contatos_emergencia')
    op.drop_index(op.f('ix_check_ins_pessoa_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_id'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_pessoas_id'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_email'), table_name='pessoas')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
